require:
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  Max: 120
  IgnoredPatterns:
    - '\s+# rubocop:disable'

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 102

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 16

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
